---
# tasks file for ansible-cp4s-role
- name: Test Role end to end
  when: operation is not defined 
  import_tasks: create-case.yml

- name: Close a case
  when: operation is defined and operation == "close_case"
  import_tasks: close-case.yml